name: Send email
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
      host: smtp.google.com
          port: 465
          account: ${{secrets.GIT_USER}}
          password: ${{secrets.GIT_PWD}}
          sender: TEST
          from: svelmurugansuresh@gmail.com
          to: svelmurugansuresh@gmail.com
          subject: Test Workflow
          body: Sample Message

      
